selection_defaults:
  min_ev: 0.00
  min_edge: 0.00
  min_kelly: 0.00
  max_kelly: 1.00
  min_odds_american: -10000
  max_odds_american: 10000
  min_model_prob: 0.00
  max_model_prob: 1.00
markets:
  #########################################################################################################################################################
  # ── Moneyline ────────────────────────────────────
  #########################################################################################################################################################
  moneyline:
    enabled: true
    pick_preference: best_prob
#    best_ev, best_prob, best_kelly
    home:
      enabled: true
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.00, 0.9999]

    away:
      enabled: true
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.55, 0.9999]

  #########################################################################################################################################################
  # ── Spread ───────────────────────────────────────
  #########################################################################################################################################################

  spread:
    enabled: true
    pick_preference: best_prob
    max_spread_abs: 100.0

    home:
      enabled: true
      line_bands:
        - [-99.0, 99.0]
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.00, 0.9999]

    away:
      enabled: true
      line_bands:
        - [-99.0, 99.0]
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.00, 0.9999]

  #########################################################################################################################################################
  # ── Totals ───────────────────────────────────────
  #########################################################################################################################################################

  total:
    enabled: true
    pick_preference: best_prob
    min_total: 0.0
    max_total: 100.0

    over:
      enabled: true

      line_bands:
        - [1.0, 100.0]
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.55, 0.9999]

    under:
      enabled: true

      line_bands:
        - [1.0, 100.0]
      odds_bands:
        - [-10000, 10000]
      edge_bands:
        - [0.00, 1.00]
      ev_bands:
        - [0.00, 1.00]
      kelly_bands:
        - [0.00, 1.00]
      prob_bands:
        - [0.55, 0.9999]
