# Feature configuration
rolling_windows:
  - 3
  - 5
  - 8

usage_features:
  - targets
  - routes_run
  - rush_attempts
  - snaps
  - air_yards

team_context_features:
  - pass_rate
  - seconds_per_play
  - proe  # pass rate over expected (if available)

opponent_strength_features:
  - def_epa_per_play_allowed
  - def_explosive_play_rate
  - def_receiver_yards_per_game

weather_features:
  - temp
  - wind
  - precip

guards:
  min_snaps: 5
  clip_quantiles: [0.005, 0.995]
