seed: 42
version_tag: auto
estimator: random_forest
random_forest:
  n_estimators: 400
  max_depth: null
  n_jobs: -1

targets:
  - qb_passing_yards
  - rb_rushing_yards
  - wr_rec_yards
  - wrte_receptions

features_path: data/features/weekly_clean.csv.gz

id_columns:
  - season
  - week
  - game_id
  - player_id
  - team_id
  - opponent_team_id
  - home_away
