# Model configuration per market
receptions:
  type: lgbm_regressor
  params:
    n_estimators: 600
    learning_rate: 0.03
    max_depth: -1
    num_leaves: 63
  sigma_floor: 0.75

receiving_yards:
  type: elastic_net
  params:
    alpha: 0.5
    l1_ratio: 0.3

rushing_yards:
  type: xgb_regressor
  params:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 6

td_anytime:
  type: logistic_regression
  params:
    C: 1.0
    class_weight: balanced
