seed: 42
version_tag: auto
estimator: random_forest
random_forest:
  n_estimators: 400
  max_depth: null
  n_jobs: -1

# Updated to match actual feature columns per Step 02.5 suggestions
targets:
  - passing_yards          # was qb_passing_yards
  - rushing_yards          # was rb_rushing_yards
  - receiving_yards        # was wr_rec_yards
  - receptions             # was wrte_receptions

features_path: data/features/weekly_clean.csv.gz

id_columns:
  - season
  - week
  - game_id
  - player_id
  - team_id
  - opponent_team_id
  - home_away
