# config/models.yml
# Stable: trains only columns we KNOW exist today (from features + logs)

seed: 42
version_tag: auto

estimator: random_forest
random_forest:
  n_estimators: 400
  max_depth: null
  n_jobs: -1

# === Trains now (confirmed present) ===
targets:
  - passing_yards
  - rushing_yards
  - receiving_yards
  - receptions
  - completions
  - passing_tds
  - interceptions
  - rushing_tds
  - targets
  - receiving_tds
  - sacks

# Add more later ONLY after columns exist in features:
#  - pass_attempts
#  - rush_attempts
#  - qb_sacks_taken
#  - qb_rush_yards
#  - qb_rush_attempts
#  - rushing_long
#  - longest_reception
#  - field_goals_made
#  - field_goals_attempted
#  - longest_field_goal
#  - kicking_points
#  - tackles_combined
#  - tackles_assists
#  - interceptions_def
#  - passes_defended
#  - anytime_td         # needs a 0/1 label
#  - team_points_for
#  - game_total_points

features_path: data/features/weekly_clean.csv.gz

id_columns:
  - season
  - week
  - game_id
  - player_id
  - team_id
  - opponent_team_id
  - home_away
