markets:

###################################################################################################
# NBA CONFIG ######################################################################################
###################################################################################################

  nba:

    moneyline:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        odds_bands:
          - [-360, -150]
        ev_min: 0.0
        ev_max: 0.20
        kelly_min: 0.0
        kelly_max: 0.25

      away:
        enabled: true
        odds_bands:
          - [-500, -156]
        ev_min: 0.0
        ev_max: 0.05
        kelly_min: 0.0
        kelly_max: 0.25

#################################################################
## NBA SPREAD ###################################################
#################################################################

    spread:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        line_bands:
          - [-13, -12]
          - [-11, -10.5]
          - [-4.5, 30.5]
        odds_bands:
          - [-300, -100]
        prob_min: 0.40
        ev_min: 0.2
        ev_max: 0.99
        kelly_min: 0.0
        kelly_max: 0.99

      away:
        enabled: true
        line_bands:
          - [-5, 2]
          - [13, 15]
        odds_bands:
          - [-300, 300]
        prob_min: 0.40
        ev_min: 0.02
        ev_max: 0.99
        kelly_min: 0.0
        kelly_max: 0.99

#################################################################
## NBA TOTAL ####################################################
#################################################################

    total:
      enabled: true
      pick_preference: best_ev

      over:
        enabled: true
        line_bands:
          - [217, 246]
        odds_bands:
          - [-130, -110]
        ev_min: 0.00
        ev_max: 0.99
        kelly_min: 0.0
        kelly_max: 0.99

      under:
        enabled: true
        line_bands:
          - [200, 246]
        odds_bands:
          - [-115, -111]
          - [-108, -107]
        ev_min: 0.00
        ev_max: 0.99
        kelly_min: 0.0
        kelly_max: 0.99

###################################################################################################
# NCAAB CONFIG ####################################################################################
###################################################################################################

  ncaab:

    moneyline:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        odds_bands:
          - [-500, -200]
          - [-199, -150]
          - [-149, -110]
          - [101, 150]
        ev_min: 0.0
        ev_max: 0.15
        kelly_min: 0.0
        kelly_max: 0.25

        exclude_rules:
          - odds_min: -149
            odds_max: -110
            ev_max: 0.04

      away:
        enabled: true
        odds_bands:
          - [-500, -200]
          - [-199, -150]
          - [-149, -110]
          - [101, 150]
        ev_min: 0.0
        ev_max: 0.15
        kelly_min: 0.0
        kelly_max: 0.25

        exclude_rules:
          - odds_min: -149
            odds_max: -110
            ev_max: 0.05

#################################################################
## NCAAB SPREAD #################################################
#################################################################

    spread:
      enabled: true
      pick_preference: best_ev

      home:
        enabled: true
        line_bands:
          - [-25, -6.5]
          - [-6.0, -3.5]
          - [-3.0, -0.5]
        ev_min: 0.0
        ev_max: 0.20
        kelly_min: 0.01
        kelly_max: 0.05

        exclude_rules:
          - line_min: -6.0
            line_max: -0.5
            ev_max: 0.03

      away:
        enabled: true
        line_bands:
          - [0.5, 4.5]
          - [5.0, 8.5]
          - [9.0, 25]
        odds_bands:
          - [-109, 100]
        ev_min: 0.0
        ev_max: 0.15
        kelly_min: 0.01
        kelly_max: 0.05

        exclude_rules:
          - line_min: 0.5
            line_max: 4.5
            ev_max: 0.02
          - line_min: 9.0
            line_max: 25
            ev_max: 0.01

#################################################################
## NCAAB TOTAL ##################################################
#################################################################

    total:
      enabled: true
      pick_preference: best_ev

      over:
        enabled: true
        line_bands:
          - [120, 134.5]
          - [135, 154.5]
          - [155, 180]
        odds_bands:
          - [-149, -110]
        ev_min: 0.05
        ev_max: 0.15
        kelly_min: 0.0
        kelly_max: 0.25

        exclude_rules:
          - line_min: 155
            line_max: 180
            ev_max: 0.09

      under:
        enabled: true
        line_bands:
          - [120, 134.5]
          - [135, 144.5]
          - [145, 155]
          - [155.5, 180]
        odds_bands:
          - [-149, -110]
        ev_min: 0.05
        ev_max: 0.10
        kelly_min: 0.0
        kelly_max: 0.25

        exclude_rules:
          - line_min: 120
            line_max: 134.5
            ev_max: 0.08
          - line_min: 145
            line_max: 155
            ev_max: 0.07
