################################################
################################################
kicking_points:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
passing_rushing_yards:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
passing_yards:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
receiving_yards:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
rushing_receiving_yards:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
rushing_yards:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
################################################
################################################
tackles:
  enabled: true
  pick_preference: best_prob

  over:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
            ################################################
  under:
    enabled: true
    actual_prop_total_*:
      - [0.0, 1000]
    pick_prob:
      - [0.00, 1.00]
    over_prob:
      - [0.00, 1.00]
    under_prob:
      - [0.00, 1.00]
