name: build-train-commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * WED"

permissions:
  contents: write

concurrency:
  group: build-train-commit-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHONUTF8: "1"
  TZ: "UTC"
  TARGET_SEASON: "2025"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas numpy joblib scikit-learn scipy pyarrow fastparquet

      # ============================
      # Build (fresh) features for TARGET_SEASON from data/weekly/latest.csv
      # ============================
      - name: Build features (TARGET_SEASON)
        run: |
          python scripts/02_build_features.py
          echo "---- features manifest ----"
          sed -n '1,10p' data/features/manifest.csv || true
          echo "---- features summary ----"
          sed -n '1,40p' data/features/_build_features_summary.txt || true

      # Optional enrichment AFTER base features exist
      - name: Enrich features (optional)
        run: |
          if [ -f scripts/02b_enrich_features.py ]; then
            python scripts/02b_enrich_features.py
          else
            echo "No scripts/02b_enrich_features.py; skipping."
          fi

      # ============================
      # Train models + manifest
      # ============================
      - name: Train models
        run: python scripts/03_train_models.py

      - name: Build models manifest (with metadata)
        run: python scripts/build_models_manifest.py

      - name: Validate manifest is populated
        run: |
          python - <<'PY'
          import sys, pandas as pd, os
          p = "models/manifest/models_manifest.csv"
          if not os.path.exists(p):
              print(f"ERROR: {p} not found.", file=sys.stderr); sys.exit(1)
          df = pd.read_csv(p)
          need = ["path","filename","sha256","target","version_tag"]
          miss = [c for c in need if c not in df.columns]
          if miss or df.empty or not df["target"].fillna("").str.len().gt(0).any():
              print("ERROR: manifest invalid or empty.", file=sys.stderr); sys.exit(1)
          print("OK: manifest valid.")
          PY

      - name: Show key outputs
        run: |
          sed -n '1,25p' output/models/metrics_summary.csv || true
          sed -n '1,25p' models/manifest/models_manifest.csv || true
          ls -lh models/pregame || true

      # ============================
      # Generate predictions for TARGET_SEASON
      # ============================
      - name: Generate pregame predictions
        run: |
          python scripts/04_predict_pregame.py --season ${TARGET_SEASON}
          echo "---- predictions written ----"
          ls -lh data/predictions/pregame || true

      # ============================
      # Props generation
      # ============================
      - name: Generate props (optional)
        run: |
          if [ -f scripts/04_generate_props.py ]; then
            python scripts/04_generate_props.py
          else
            echo "No scripts/04_generate_props.py; skipping."
          fi

      - name: Season guard on props_current.csv (must be 2025)
        run: |
          set -e
          P="data/props/props_current.csv"
          if [ ! -s "$P" ]; then
            echo "ERROR: $P missing or empty after generation"; exit 1
          fi
          python - <<'PY'
          import os, pandas as pd, sys
          want = int(os.getenv("TARGET_SEASON","2025"))
          p = "data/props/props_current.csv"
          df = pd.read_csv(p)
          if "season" not in df.columns:
              print("ERROR: props_current.csv missing 'season' column", file=sys.stderr); sys.exit(1)
          mx = int(pd.to_numeric(df["season"], errors="coerce").max())
          print("props_current.csv max(season)=", mx)
          if mx != want:
              print(f"ERROR: props_current.csv is season {mx}, not {want}.", file=sys.stderr)
              sys.exit(1)
          PY

      - name: Show props outputs
        run: |
          ls -lh data/props || true
          sed -n '1,20p' data/props/props_current.csv 2>/dev/null || true
          for f in data/props/props_*.csv; do
            [ -f "$f" ] && echo "---- $f ----" && sed -n '1,5p' "$f";
          done

      # ============================
      # Probability calibration
      # ============================
      - name: Verify historical outcomes present
        run: |
          set -e
          if [ ! -s "data/props/history_props_with_outcomes.csv" ]; then
            echo "ERROR: data/props/history_props_with_outcomes.csv missing or empty. Run finalize-props first."; exit 1
          fi

      - name: Train calibrators
        run: |
          set -e
          python scripts/05_train_calibrator.py \
            --csv "data/props/history_props_with_outcomes.csv" \
            --method auto \
            --outdir "models/calibration"
          ls -lh models/calibration
          ls models/calibration/*.joblib >/dev/null 2>&1 || (echo "ERROR: No calibrator joblibs produced"; exit 1)

      - name: Apply calibrators
        run: |
          python scripts/06_apply_calibrator.py \
            --csv_in "data/props/props_current.csv" \
            --csv_out "data/props/props_current_calibrated.csv" \
            --calib_dir "models/calibration"

      - name: Season guard on props_current_calibrated.csv (must be 2025)
        run: |
          set -e
          P="data/props/props_current_calibrated.csv"
          if [ ! -s "$P" ]; then
            echo "ERROR: $P not found after apply."; exit 1
          fi
          python - <<'PY'
          import os, pandas as pd, sys
          want = int(os.getenv("TARGET_SEASON","2025"))
          p = "data/props/props_current_calibrated.csv"
          df = pd.read_csv(p)
          mx = int(pd.to_numeric(df["season"], errors="coerce").max())
          print("props_current_calibrated.csv max(season)=", mx)
          if mx != want:
            print(f"ERROR: props_current_calibrated.csv season {mx} != {want}.", file=sys.stderr); sys.exit(1)
          PY

      # ============================
      # Commit + upload
      # ============================
      - name: Ensure .gitignore excludes joblibs
        run: |
          if [ -f .gitignore ]; then
            grep -q "^models/pregame/.*\.joblib$" .gitignore || echo "models/pregame/*.joblib" >> .gitignore
            grep -q "^models/calibration/.*\.joblib$" .gitignore || echo "models/calibration/*.joblib" >> .gitignore
          else
            printf "models/pregame/*.joblib\nmodels/calibration/*.joblib\n" > .gitignore
          fi

      - name: Commit calibration summary + calibrated props + manifest/metrics/logs
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .gitignore models/manifest/*               2>/dev/null || true
          git add output/models/metrics_summary.csv          2>/dev/null || true
          git add output/logs/*.log                          2>/dev/null || true
          git add models/calibration/calibration_summary.csv 2>/dev/null || true
          git add data/props/props_current_calibrated.csv    2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "Pipeline ${{ github.run_id }}: calibration summary + calibrated props + manifest/metrics/logs (season ${TARGET_SEASON})"
            git fetch origin main || true
            git pull --rebase --autostash origin main || true
            git push
          else
            echo "No lightweight changes to commit."
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-train-commit-${{ github.run_id }}
          path: |
            models/pregame/*.joblib
            models/calibration/*.joblib
            data/props/props_current.csv
            data/props/props_current_calibrated.csv
          if-no-files-found: warn
          retention-days: 90
