name: build-train-commit

on:
  # run manually from the Actions tab
  workflow_dispatch:
  # run automatically every Wednesday 11:00 UTC ≈ 7:00 AM ET (DST-aware note: cron is UTC)
  schedule:
    - cron: "0 11 * * WED"

permissions:
  contents: write

concurrency:
  group: build-train-commit-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHONUTF8: "1"
  TZ: "UTC"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Enrich features (optional)
        run: |
          if [ -f scripts/02b_enrich_features.py ]; then
            python scripts/02b_enrich_features.py
          else
            echo "No scripts/02b_enrich_features.py; skipping."
          fi

      # ============================
      # Train models + manifest
      # ============================
      - name: Train models
        run: python scripts/03_train_models.py

      - name: Build models manifest (with metadata)
        run: python scripts/build_models_manifest.py

      - name: Validate manifest is populated
        run: |
          python - <<'PY'
          import sys, pandas as pd, os
          p = "models/manifest/models_manifest.csv"
          if not os.path.exists(p):
              print(f"ERROR: {p} not found.", file=sys.stderr); sys.exit(1)
          df = pd.read_csv(p)
          need = ["path","filename","sha256","target","version_tag"]
          miss = [c for c in need if c not in df.columns]
          if miss or df.empty or not df["target"].fillna("").str.len().gt(0).any():
              print("ERROR: manifest invalid or empty.", file=sys.stderr); sys.exit(1)
          print("OK: manifest valid.")
          PY

      - name: Show key outputs
        run: |
          sed -n '1,25p' output/models/metrics_summary.csv || true
          sed -n '1,25p' models/manifest/models_manifest.csv || true
          ls -lh models/pregame || true

      # ============================
      # Props generation (optional)
      # ============================
      - name: Generate props (optional)
        run: |
          if [ -f scripts/04_generate_props.py ]; then
            python scripts/04_generate_props.py
          else
            echo "No scripts/04_generate_props.py; skipping."
          fi

      # ============================
      # Probability calibration
      # ============================
      - name: Train calibrators (auto-select isotonic/sigmoid)
        run: |
          if [ -f scripts/05_train_calibrator.py ]; then
            if [ -f "data/props/history_props_with_outcomes.csv" ]; then
              python scripts/05_train_calibrator.py \
                --csv "data/props/history_props_with_outcomes.csv" \
                --method auto \
                --outdir "models/calibration"
            else
              echo "No historical props file; skipping calibration."
            fi
          else
            echo "No scripts/05_train_calibrator.py; skipping."
          fi

      - name: Apply calibrators to current props
        run: |
          if [ -f scripts/06_apply_calibrator.py ] && [ -f "data/props/props_current.csv" ]; then
            if ls models/calibration/*.joblib >/dev/null 2>&1; then
              python scripts/06_apply_calibrator.py \
                --csv_in "data/props/props_current.csv" \
                --csv_out "data/props/props_current_calibrated.csv" \
                --calib_dir "models/calibration"
            else
              echo "No calibrators found; skipping apply."
            fi
          else
            echo "Missing script or props_current.csv; skipping apply."
          fi

      - name: Show calibration outputs
        run: |
          sed -n '1,25p' models/calibration/calibration_summary.csv || true
          sed -n '1,25p' data/props/props_current_calibrated.csv || true
          ls -lh models/calibration || true

      # ============================
      # Selection & Staking
      # ============================
      - name: Compute probability edges (optional)
        run: |
          if [ -f scripts/06_probability_and_edge.py ]; then
            python scripts/06_probability_and_edge.py || true
          else
            echo "No scripts/06_probability_and_edge.py; skipping."
          fi

      - name: Select bets & staking (optional)
        run: |
          if [ -f scripts/07_select_bets.py ]; then
            if ls output/*edges*.csv >/dev/null 2>&1; then
              python scripts/07_select_bets.py
            else
              echo "No *edges*.csv files found in output/; skipping selection & staking."
            fi
          else
            echo "No scripts/07_select_bets.py; skipping."
          fi

      - name: Show selection outputs
        run: |
          ls -lh output || true
          ls -lh output/*best_bets* 2>/dev/null || true
          sed -n '1,25p' output/*best_bets* 2>/dev/null || true

      # ============================
      # Git hygiene + commit light artifacts
      # ============================
      - name: Ensure .gitignore excludes joblibs
        run: |
          if [ -f .gitignore ]; then
            grep -q "^models/pregame/.*\.joblib$" .gitignore || echo "models/pregame/*.joblib" >> .gitignore
            grep -q "^models/calibration/.*\.joblib$" .gitignore || echo "models/calibration/*.joblib" >> .gitignore
          else
            printf "models/pregame/*.joblib\nmodels/calibration/*.joblib\n" > .gitignore
          fi

      - name: Commit lightweight outputs (manifest/metrics/logs only)
        run: |
          set -e
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .gitignore models/manifest/* || true
          git add output/models/metrics_summary.csv || true
          git add output/logs/*.log || true
          git add models/calibration/calibration_summary.csv || true
          git add data/props/props_current_calibrated.csv || true
          git add output/*best_bets* 2>/dev/null || true
          if ! git diff --cached --quiet; then
            git commit -m "Pipeline ${{ github.run_id }}: manifest, metrics, logs, calibration summary, calibrated props, best bets"
            git push
          else
            echo "No lightweight changes to commit."
          fi

      # ============================
      # Upload artifacts & releases
      # ============================
      - name: Upload model artifacts (90-day retention)
        uses: actions/upload-artifact@v4
        with:
          name: models-pregame-${{ github.run_id }}
          path: models/pregame/*.joblib
          if-no-files-found: warn
          retention-days: 90

      - name: Upload calibration artifacts (90-day retention)
        uses: actions/upload-artifact@v4
        with:
          name: models-calibration-${{ github.run_id }}
          path: models/calibration/*.joblib
          if-no-files-found: warn
          retention-days: 90

      - name: Upload best-bets outputs (90-day retention)
        uses: actions/upload-artifact@v4
        with:
          name: best-bets-${{ github.run_id }}
          path: |
            output/*best_bets*
          if-no-files-found: warn
          retention-days: 90

      - name: Create or update 'latest-models' release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-models
          name: Latest Models
          prerelease: true
          files: |
            models/pregame/*.joblib
            models/calibration/*.joblib
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create immutable run release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: models-${{ github.run_number }}
          name: Models Run ${{ github.run_number }}
          prerelease: true
          files: |
            models/pregame/*.joblib
            models/calibration/*.joblib
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
