name: build-train-commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * WED"  # every Wednesday 11:00 UTC

permissions:
  contents: write

concurrency:
  group: build-train-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  train:
    name: Train calibrators and update calibrated props
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      TARGET_SEASON: '2025'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify finalized outcomes exist
        run: |
          test -s data/props/history_props_with_outcomes.csv || \
            (echo "Missing outcomes: run finalize-props after games complete." && exit 1)

      - name: Train calibrators
        run: |
          python scripts/10_train_calibrators.py \
            --in data/props/history_props_with_outcomes.csv \
            --out models/calibrators.joblib
          test -s models/calibrators.joblib

      - name: Clean stale current props (pre-apply)
        run: rm -f data/props/props_current_calibrated.csv

      - name: Apply calibrators to current props (if present)
        run: |
          if [ -f data/props/props_current.csv ]; then
            python scripts/11_apply_calibrators.py \
              --in data/props/props_current.csv \
              --model models/calibrators.joblib \
              --out data/props/props_current_calibrated.csv
            test -s data/props/props_current_calibrated.csv
          else
            echo "props_current.csv not found; skipping apply."
          fi

      - name: Validate calibrated (optional)
        run: |
          if [ -f data/props/props_current_calibrated.csv ]; then
            python scripts/99_validate_csv.py data/props/props_current_calibrated.csv || true
          fi

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit updated models & calibrated props
        run: |
          git add models/*.joblib data/props/props_current_calibrated.csv
          git commit -m "chore: train calibrators + update calibrated props" || echo "No changes"
          git push

      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: train-and-apply-outputs
          path: |
            models/*.joblib
            data/props/props_current_calibrated.csv
          if-no-files-found: warn
          retention-days: 90
