name: finalize-props

on:
  workflow_dispatch:
  schedule:
    # Finalize after TNF and after MNF/week conclusion
    - cron: "0 9 * * 2"  # Tue 09:00 UTC (post-MNF)
    - cron: "0 9 * * 5"  # Fri 09:00 UTC (post-TNF)

permissions:
  contents: write

jobs:
  finalize:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout (full history for rebase)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyarrow fastparquet || true

      - name: Show inputs (if present)
        run: |
          ls -lh data/props/history_pending.csv 2>/dev/null || echo "no pending file"
          ls -lh data/weekly/latest.csv         2>/dev/null || echo "no weekly latest"

      - id: check_pending
        name: Check for pending file
        run: |
          set -e
          if [ -f "data/props/history_pending.csv" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
            echo "Found data/props/history_pending.csv"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
            mkdir -p output/summaries
            msg="[$(date -u +%Y-%m-%dT%H:%M:%SZ)] finalize-props: no pending props file found (data/props/history_pending.csv). Skipping finalize."
            echo "$msg" | tee "output/summaries/finalize_no_pending_${GITHUB_RUN_ID}.log"
          fi

      - name: Finalize props → stamp outcomes
        if: steps.check_pending.outputs.exists == 'true'
        run: |
          set -e
          python scripts/08_finalize_props_outcomes.py \
            --pending data/props/history_pending.csv \
            --weekly  data/weekly/latest.csv \
            --out     data/props/history_props_with_outcomes.csv \
            --join    player_week

      - name: Show outputs
        if: steps.check_pending.outputs.exists == 'true'
        run: |
          sed -n '1,20p' data/props/history_props_with_outcomes.csv 2>/dev/null || true
          wc -l data/props/history_props_with_outcomes.csv 2>/dev/null || true

      - name: Commit finalized history (only if outcomes exist)
        if: steps.check_pending.outputs.exists == 'true'
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git rebase origin/main || git merge --no-edit origin/main

          if [ -f data/props/history_props_with_outcomes.csv ]; then
            git add -f data/props/history_props_with_outcomes.csv
          fi
          git rm -f data/props/history_pending.csv 2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No finalized history changes to commit."
            exit 0
          fi

          git commit -m "Finalize props outcomes: update history_props_with_outcomes.csv (run $GITHUB_RUN_ID)"
          git push origin HEAD:main

      - name: Upload finalized history (artifact, 90-day retention)
        if: steps.check_pending.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: history-props-with-outcomes-${{ github.run_id }}
          path: data/props/history_props_with_outcomes.csv
          if-no-files-found: warn
          retention-days: 90

      - name: Upload “no pending” summary (artifact)
        if: steps.check_pending.outputs.exists != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: finalize-no-pending-${{ github.run_id }}
          path: output/summaries/finalize_no_pending_${{ github.run_id }}.log
          if-no-files-found: warn
          retention-days: 90
