name: Import Project Items from CSV
on: workflow_dispatch
permissions:
  contents: read
  issues: write
  projects: write
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: echo "Workflow stub is in place"
