name: Injuries Source Probe (ESPN)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml html5lib

      - name: Probe ESPN injuries
        run: |
          python - <<'PY'
import pandas as pd, os, sys
url = "https://www.espn.com/nfl/injuries"
tables = pd.read_html(url)  # requires lxml
rows = sum(len(t) for t in tables)
print(f"[probe] ESPN injuries tables: {len(tables)} tables, {rows} total rows")
# Save a simple combined CSV so we can inspect structure
outdir = "data/raw/injuries"
os.makedirs(outdir, exist_ok=True)
combined = pd.concat(tables, ignore_index=True, sort=False)
combined.to_csv(os.path.join(outdir, "_probe_espn_injuries.csv"), index=False)
PY

      - name: Upload probe artifact
        uses: actions/upload-artifact@v4
        with:
          name: espn-injuries-probe
          path: data/raw/injuries/_probe_espn_injuries.csv
