name: Injuries Source Probe (ESPN)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (pandas + lxml)
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml html5lib

      - name: Probe ESPN injuries
        run: |
          python -c "import pandas as pd, os; \
url='https://www.espn.com/nfl/injuries'; \
tables=pd.read_html(url); \
rows=sum(len(t) for t in tables); \
print(f'[probe] ESPN injuries: {len(tables)} tables, {rows} rows'); \
os.makedirs('data/raw/injuries', exist_ok=True); \
pd.concat(tables, ignore_index=True, sort=False).to_csv('data/raw/injuries/_probe_espn_injuries.csv', index=False)"

      - name: Upload probe artifact
        uses: actions/upload-artifact@v4
        with:
          name: espn-injuries-probe
          path: data/raw/injuries/_probe_espn_injuries.csv
