name: models-manifest

on:
  workflow_dispatch:
  schedule:
    # Example: run daily at 3:00 UTC
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy pyyaml joblib
          fi

      - name: Build models manifest
        run: |
          python scripts/build_models_manifest.py

      - name: Commit manifest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/manifest/models_manifest.csv
          git add models/manifest/models_manifest.lock.json
          git commit -m "chore: update models manifest" || echo "No changes"
          git push
