name: NFL Props Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily 6AM UTC run

permissions:
  contents: write

jobs:
  build-train-commit:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Data prep ---
      - name: Step 01 - Canonicalize raw data
        run: python scripts/01_canonicalize_raw.py

      - name: Step 02 - Build features
        run: python scripts/02_build_features.py

      - name: Step 02.5 - Debug features (optional)
        run: |
          if [ -f scripts/02a_debug_features.py ]; then
            python scripts/02a_debug_features.py
          else
            echo "No scripts/02a_debug_features.py; skipping."
          fi

      - name: Step 02.6 - Enrich features
        run: python scripts/02b_enrich_features.py

      # --- Model training ---
      - name: Step 03 - Train models
        run: python scripts/03_train_models.py

      # --- Manifest build ---
      - name: Step 03.5 - Build models manifest
        run: python scripts/build_models_manifest.py models/pregame output/logs/features_columns.txt

      # --- Commit results back ---
      - name: Commit updated models, metrics, and manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git lfs track "*.joblib"

          git add models/pregame/*.joblib
          git add models/manifest/models_manifest.csv
          git add models/manifest/models_manifest.lock.json || true
          git add output/models/metrics_summary.csv
          git add output/logs/features_columns.txt

          git commit -m "[skip ci] Update models, manifest and metrics" || echo "No changes to commit"
          git push

      # --- Upload artifacts for inspection ---
      - name: Upload models and logs
        uses: actions/upload-artifact@v4
        with:
          name: models-and-logs
          path: |
            models/pregame/*.joblib
            models/manifest/models_manifest.csv
            models/manifest/models_manifest.lock.json
            output/models/metrics_summary.csv
            output/logs/features_columns.txt

      # --- Props generation ---
      - name: Step 04 - Generate props
        run: python scripts/04_generate_props.py
