name: NFL Props Pipeline

on:
  workflow_dispatch:
    inputs:
      pull_odds:
        description: "Pull odds via API (if script present)? 1=yes, 0=no"
        required: true
        default: "0"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
      PULL_ODDS: ${{ github.event.inputs.pull_odds }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy nfl_data_py scikit-learn lightgbm scipy requests
          fi

      - name: Step 01 (Pull NFL data)
        run: |
          if [ -f scripts/01_pull_nflverse_chunked.py ]; then
            python scripts/01_pull_nflverse_chunked.py --start 2019 --end 2024 --chunk-years 3
          else
            python scripts/01_pull_nflverse.py --start 2019 --end 2024
          fi

      - name: Step 02 (Build features)
        run: python scripts/02_build_features.py

      - name: Step 03 (Train models)
        run: |
          if [ -f scripts/03_train_models.py ]; then
            python scripts/03_train_models.py
          else
            echo "skip: scripts/03_train_models.py not found"
          fi

      - name: Step 04 (Generate props)
        run: |
          if [ -f scripts/04_generate_props.py ]; then
            python scripts/04_generate_props.py
          else
            echo "ERROR: scripts/04_generate_props.py not found" && exit 1
          fi

      - name: Step 05 (Rank edges - no odds)
        run: python scripts/05_rank_edges_no_odds.py

      # Game projections (optional; run if scripts exist)
      - name: G1 (Build game features)
        run: |
          if [ -f scripts/G1_build_game_features.py ]; then
            python scripts/G1_build_game_features.py
          else
            echo "skip: scripts/G1_build_game_features.py not found"
          fi

      - name: G2 (Predict games)
        run: |
          if [ -f scripts/G2_predict_games.py ]; then
            python scripts/G2_predict_games.py
          else
            echo "skip: scripts/G2_predict_games.py not found"
          fi

      # Odds via The Odds API (toggle + only if script exists)
      - name: Step 06 (Pull odds via The Odds API)
        if: ${{ env.PULL_ODDS == '1' }}
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          if [ -f scripts/06_pull_odds_api.py ]; then
            python scripts/06_pull_odds_api.py
          else
            echo "skip: scripts/06_pull_odds_api.py not found"
          fi

      - name: Debug — odds summary (if any)
        if: ${{ env.PULL_ODDS == '1' }}
        run: |
          [ -f data/odds/_api_summary.txt ] && sed -n '1,160p' data/odds/_api_summary.txt || echo "no _api_summary.txt"

      - name: Commit outputs
        env:
          GH_USER_NAME: "github-actions[bot]"
          GH_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          set -e
          git config user.name "$GH_USER_NAME"
          git config user.email "$GH_USER_EMAIL"

          # Features
          git add -f data/features/*.parquet 2>/dev/null || true
          git add -f data/features/*.csv.gz 2>/dev/null || true
          git add -f data/features/manifest.csv 2>/dev/null || true

          # Predictions / Props
          git add -f data/predictions/*.csv 2>/dev/null || true
          git add -f data/props/*.csv 2>/dev/null || true

          # Edges (compressed + preview)
          git add -f data/edges/*.csv.gz 2>/dev/null || true
          git add -f data/edges/*.preview.csv 2>/dev/null || true
          git add -f data/edges/*.csv 2>/dev/null || true

          # Odds (only if present)
          git add -f data/odds/*.csv 2>/dev/null || true
          git add -f data/odds/_api_summary.txt 2>/dev/null || true

          # Games
          git add -f data/games/*.csv 2>/dev/null || true

          # Outputs
          git add -f output/*.csv 2>/dev/null || true
          git add -f output/*.json 2>/dev/null || true

          git diff --staged --quiet || git commit -m "Pipeline outputs (props, edges, games, odds-if-present)"
          git push
