name: NFL Props Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily 6AM UTC run

permissions:
  contents: write

jobs:
  build-train-commit:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Data prep ---
      - name: Step 01 - Canonicalize raw data
        run: python scripts/01_canonicalize_raw.py

      - name: Step 02 - Build features
        run: python scripts/02_build_features.py

      - name: Step 02.5 - Debug features (optional)
        run: |
          if [ -f scripts/02a_debug_features.py ]; then
            python scripts/02a_debug_features.py
          else
            echo "No scripts/02a_debug_features.py; skipping."
          fi

      - name: Step 02.6 - Enrich features
        run: python scripts/02b_enrich_features.py

      # --- Model training ---
      - name: Step 03 - Train models
        run: python scripts/03_train_models.py

      # --- Manifest build ---
      - name: Step 03.5 - Build models manifest
        run: python scripts/build_models_manifest.py models/pregame output/logs/features_columns.txt

      # --- Commit results (models/manifest/logs) ---
      - name: Commit updated models, metrics, and manifest
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git lfs track "*.joblib" || true

          git add models/pregame/*.joblib 2>/dev/null || true
          git add models/manifest/models_manifest.csv 2>/dev/null || true
          git add models/manifest/models_manifest.lock.json 2>/dev/null || true
          git add output/models/metrics_summary.csv 2>/dev/null || true
          git add output/logs/features_columns.txt 2>/dev/null || true

          git commit -m "[skip ci] Update models, manifest and metrics" || echo "No changes to commit (models/manifest)."
          git push || true

      # --- Upload artifacts for inspection (models/logs) ---
      - name: Upload models and logs
        uses: actions/upload-artifact@v4
        with:
          name: models-and-logs
          path: |
            models/pregame/*.joblib
            models/manifest/models_manifest.csv
            models/manifest/models_manifest.lock.json
            output/models/metrics_summary.csv
            output/logs/features_columns.txt
          if-no-files-found: warn

      # --- Props generation ---
      - name: Step 04 - Generate props
        run: |
          set -e
          if [ -f scripts/04_generate_props.py ]; then
            python scripts/04_generate_props.py
          else
            echo "ERROR: scripts/04_generate_props.py missing"; exit 1
          fi

      - name: Verify props generated (fail loud if missing)
        run: |
          set -e
          test -s data/props/props_current.csv || (echo "ERROR: data/props/props_current.csv not found/empty after generation" && exit 1)
          echo "--- props_current.csv (head) ---"
          sed -n '1,20p' data/props/props_current.csv || true
          echo "--- data/props listing ---"
          ls -lh data/props || true

      - name: Commit props outputs (props_current + per-market)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true

          git add -f data/props/props_current.csv 2>/dev/null || true
          find data/props -maxdepth 1 -type f -name 'props_*.csv' -print0 2>/dev/null | xargs -0 -r git add

          if git diff --cached --quiet; then
            echo "No props changes to commit."
          else
            git commit -m "[props] update props_current and per-market (run $GITHUB_RUN_ID)"
            git push
          fi

      - name: Upload props artifacts (for reference)
        uses: actions/upload-artifact@v4
        with:
          name: props-${{ github.run_id }}
          path: data/props/*.csv
          if-no-files-found: warn
