name: NFL Props Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily 06:00 UTC

permissions:
  contents: write

jobs:
  props:
    name: Build current & calibrated props
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TARGET_SEASON: '2025'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure data dirs
        run: mkdir -p data/props data/logs

      - name: Clean stale current props
        run: rm -f data/props/props_current.csv

      - name: Fetch odds / props
        run: python scripts/01_fetch_odds_props.py --out data/props/props_raw.csv

      - name: Build current props
        run: |
          python scripts/02_build_props_current.py \
            --in data/props/props_raw.csv \
            --out data/props/props_current.csv
          test -s data/props/props_current.csv

      - name: Calibrate props (if model available)
        run: |
          if [ -f models/calibrators.joblib ]; then
            python scripts/03_calibrate_props.py \
              --in data/props/props_current.csv \
              --out data/props/props_current_calibrated.csv
          else
            echo "No calibrators found; skipping calibration."
          fi

      - name: Validate calibrated (optional)
        run: |
          if [ -f data/props/props_current_calibrated.csv ]; then
            python scripts/99_validate_csv.py data/props/props_current_calibrated.csv || true
          fi

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit updated props
        run: |
          git add data/props/props_current*.csv
          git commit -m "chore: update current props (pipeline)" || echo "No changes"
          git push

      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v4
        with:
          name: props-pipeline-outputs
          path: data/props/*.csv
          if-no-files-found: warn
          retention-days: 14
