name: Build NFL Player & Game Projections

on:
  workflow_dispatch:
    inputs:
      pull_odds:
        description: "Pull odds data? (1=yes, 0=no)"
        required: true
        default: "1"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
      PULL_ODDS: ${{ github.event.inputs.pull_odds }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy nfl_data_py scikit-learn lightgbm scipy
          fi

      - name: Step 01 - Pull NFL data
        run: python scripts/01_pull_nflverse.py

      - name: Step 02 - Build features
        run: python scripts/02_build_features.py

      - name: Step 03 - Train models
        run: python scripts/03_train_models.py

      - name: Step 04 - Predict player props
        run: python scripts/04_predict.py

      - name: Step G1 - Build game features
        run: python scripts/G1_build_game_features.py

      - name: Step G2 - Predict games
        run: python scripts/G2_predict_games.py

      - name: Step 05 - Pull odds & merge
        if: env.PULL_ODDS == '1'
        run: python scripts/05_pull_odds_merge.py

      - name: Step 06 - Probability & edge
        if: env.PULL_ODDS == '1'
        run: python scripts/06_probability_and_edge.py

      - name: Step 07 - Select bets
        if: env.PULL_ODDS == '1'
        run: python scripts/07_select_bets.py

      - name: Commit updated data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/ output/
          git commit -m "Auto-update projections and outputs" || echo "No changes"
          git push
