name: NFL Props Pipeline
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run (pull + features only)
        run: |
          set -e
          if [ -f scripts/01_pull_nflverse_chunked.py ]; then
            python scripts/01_pull_nflverse_chunked.py --start 2019 --end 2024 --chunk-years 3
          else
            python scripts/01_pull_nflverse.py --start 2019 --end 2024
          fi
          python scripts/02_build_features.py

      - name: Commit outputs
        env:
          GH_USER_NAME: "github-actions[bot]"
          GH_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "$GH_USER_NAME"
          git config user.email "$GH_USER_EMAIL"
          git add data/features/*.parquet || true
          git add data/features/*.csv.gz || true
          git add data/features/manifest.csv || true
          git diff --staged --quiet || git commit -m "Update features + manifest"
          git push
