name: NFL Props Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"  # daily 06:00 UTC

permissions:
  contents: write

jobs:
  props:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TARGET_SEASON: '2025'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Fetch odds / props
        run: python scripts/01_fetch_odds.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

      - name: Step 01 - Canonicalize raw data
        run: python scripts/01_canonicalize_raw.py

      - name: Step 02 - Build features
        run: python scripts/02_build_features.py

      - name: Step 02.5 - Debug features (optional)
        run: |
          if [ -f scripts/02a_debug_features.py ]; then
            python scripts/02a_debug_features.py
          else
            echo "No scripts/02a_debug_features.py; skipping."
          fi

      - name: Step 02.6 - Enrich features (optional)
        run: |
          if [ -f scripts/02b_enrich_features.py ]; then
            python scripts/02b_enrich_features.py
          else
            echo "No scripts/02b_enrich_features.py; skipping."
          fi

      - name: Step 03 - Train models
        run: python scripts/03_train_models.py

      - name: Step 03.5 - Build models manifest
        run: python scripts/build_models_manifest.py models/pregame output/logs/features_columns.txt

      - name: Step 03.9 - Generate predictions
        run: python scripts/04_predict.py --season "${TARGET_SEASON}"

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit models, manifest, features, predictions
        run: |
          git add models/ manifest output/ data/predictions/ -f || true
          git commit -m "[ci] update models/manifest/predictions" || true
          git push || true

      - name: Upload models/logs (debug)
        uses: actions/upload-artifact@v4
        with:
          name: models-and-logs
          path: |
            models/pregame/*.joblib
            models/manifest/*
            output/models/metrics_summary.csv
            output/logs/features_columns.txt
          if-no-files-found: warn

      - name: Step 04 - Generate props
        run: python scripts/04_generate_props.py

      - name: Verify props generated
        run: test -s data/props/props_current.csv

      - name: Commit props outputs
        run: |
          git add data/props/props_current*.csv -f || true
          git commit -m "[props] update props_current" || true
          git push || true

      - name: Upload props artifacts
        uses: actions/upload-artifact@v4
        with:
          name: props-${{ github.run_id }}
          path: data/props/*.csv
          if-no-files-found: warn
