name: NFL Props Pipeline

on:
  workflow_dispatch:
    inputs:
      pull_odds:
        description: "Pull odds via API (if script present)? 1=yes, 0=no"
        required: true
        default: "0"
      forecast_season:
        description: "Pregame season (e.g., 2025) — leave blank to skip"
        required: false
        default: ""
      forecast_week:
        description: "Pregame week (e.g., 1) — leave blank to skip"
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: nfl-props-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
      PULL_ODDS: ${{ github.event.inputs.pull_odds }}
      FORECAST_SEASON: ${{ github.event.inputs.forecast_season }}
      FORECAST_WEEK: ${{ github.event.inputs.forecast_week }}
      LOG_FILE: _logs/pipeline.log

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create log and base dirs
        run: |
          mkdir -p _logs
          echo "=== $(date -Is) :: START RUN ===" | tee -a "$LOG_FILE"
          mkdir -p data/raw data/features data/predictions output/models models/pregame

      - name: Install Python deps
        run: |
          set -euo pipefail
          {
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            else
              pip install pandas numpy nfl_data_py scikit-learn lightgbm scipy requests joblib lxml html5lib
            fi
          } 2>&1 | tee -a "$LOG_FILE"
          test ${PIPESTATUS[0]} -eq 0

      - name: Step 01 — Pull/canonicalize (if present)
        run: |
          set -euo pipefail
          {
            if [ -f scripts/01_pull_nflverse.py ]; then
              YEND=$(date +%Y)
              python scripts/01_pull_nflverse.py --start 2024 --end "$YEND"
            elif [ -f scripts/01_pull_nflverse_chunked.py ]; then
              YEND=$(date +%Y)
              python scripts/01_pull_nflverse_chunked.py --start 2024 --end "$YEND" --chunk-years 2
            else
              echo "SKIP: no Step 01 script found"
            fi
          } 2>&1 | tee -a "$LOG_FILE"
          test ${PIPESTATUS[0]} -eq 0

      - name: Step 02 — Build features (if present)
        run: |
          set -euo pipefail
          {
            if [ -f scripts/02_build_features.py ]; then
              python scripts/02_build_features.py
            else
              echo "SKIP: scripts/02_build_features.py not found"
            fi
          } 2>&1 | tee -a "$LOG_FILE"
          test ${PIPESTATUS[0]} -eq 0

      - name: Step 03 — Train models (if present)
        run: |
          set -euo pipefail
          {
            if [ -f scripts/03_train_models.py ]; then
              python scripts/03_train_models.py
            else
              echo "SKIP: scripts/03_train_models.py not found"
            fi
          } 2>&1 | tee -a "$LOG_FILE"
          test ${PIPESTATUS[0]} -eq 0

      - name: Step 04 — Pregame predictions (if present)
        run: |
          set -euo pipefail
          {
            if [ -f scripts/04_predict_pregame.py ]; then
              python scripts/04_predict_pregame.py
            else
              echo "SKIP: scripts/04_predict_pregame.py not found"
            fi
          } 2>&1 | tee -a "$LOG_FILE"
          test ${PIPESTATUS[0]} -eq 0

      - name: Finalize log
        if: always()
        run: |
          echo "=== $(date -Is) :: END RUN (status=${{ job.status }}) ===" | tee -a "$LOG_FILE"

      - name: Upload log artifact (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs-${{ github.run_id }}
          path: _logs/pipeline.log
          if-no-files-found: error
          retention-days: 7

      - name: Upload outputs (best-effort)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          path: |
            output/**
            data/predictions/**
            models/pregame/**
          if-no-files-found: warn
          retention-days: 7
