name: NFL Props Pipeline

on:
  workflow_dispatch:
    inputs:
      pull_odds:
        description: "Pull odds via API (if script present)? 1=yes, 0=no"
        required: true
        default: "0"
      forecast_season:
        description: "Pregame season (e.g., 2025) — leave blank to skip"
        required: false
        default: ""
      forecast_week:
        description: "Pregame week (e.g., 1) — leave blank to skip"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
      PULL_ODDS: ${{ github.event.inputs.pull_odds }}
      FORECAST_SEASON: ${{ github.event.inputs.forecast_season }}
      FORECAST_WEEK: ${{ github.event.inputs.forecast_week }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy nfl_data_py scikit-learn lightgbm scipy requests joblib lxml html5lib
          fi

      # --- Detect & back up existing roster (optional seed) ---
      - name: Detect and back up existing roster
        run: |
          mkdir -p tmp
          if [ -f data/raw/nflverse/rosters_latest.csv.gz ]; then
            echo "HAVE_SEEDED_ROSTER=1" >> $GITHUB_ENV
            cp -f data/raw/nflverse/rosters_latest.csv.gz tmp/rosters_latest.seed.gz
            echo "Found pre-seeded roster; backed up to tmp/rosters_latest.seed.gz"
          else
            echo "HAVE_SEEDED_ROSTER=0" >> $GITHUB_ENV
            echo "No pre-seeded roster detected"
          fi

      # --- R setup & rosters (skip if rosters already exist) ---
      - name: Set up R
        if: ${{ hashFiles('data/raw/nflverse/rosters_latest.csv.gz') == '' }}
        uses: r-lib/actions/setup-r@v2

      - name: Set up R dependencies
        if: ${{ hashFiles('data/raw/nflverse/rosters_latest.csv.gz') == '' }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::remotes
            any::nflreadr

      - name: Pull rosters via nflreadr (R) — latest only (2024+)
        if: ${{ hashFiles('data/raw/nflverse/rosters_latest.csv.gz') == '' }}
        run: |
          Rscript -e "yrs <- 2024:as.integer(format(Sys.Date(), '%Y'));
                      df <- nflreadr::load_rosters(yrs);
                      dir.create('data/raw/nflverse', recursive=TRUE, showWarnings=FALSE);
                      fn <- 'data/raw/nflverse/rosters_latest.csv.gz';
                      write.csv(df, gzfile(fn), row.names=FALSE)"

      # --- Restore pre-seeded roster (if backed up) ---
      - name: Restore pre-seeded roster (if backed up)
        if: ${{ env.HAVE_SEEDED_ROSTER == '1' }}
        run: |
          if [ -f tmp/rosters_latest.seed.gz ]; then
            cp -f tmp/rosters_latest.seed.gz data/raw/nflverse/rosters_latest.csv.gz
            echo "Restored pre-seeded roster after data pulls."
          fi

      # ===== Core pulls (PBP + canonicalize WEEKLY/ROSTERS) =====
      - name: Step 01 (Pull NFL data and canonicalize)
        run: |
          YEND=$(date +%Y)
          if [ -f scripts/01_pull_nflverse.py ]; then
            python scripts/01_pull_nflverse.py --start 2024 --end "$YEND"
          elif [ -f scripts/01_pull_nflverse_chunked.py ]; then
            python scripts/01_pull_nflverse_chunked.py --start 2024 --end "$YEND" --chunk-years 2
          else
            echo "ERROR: no Step 01 script found" && exit 1
          fi

      - name: Finalize weekly/rosters tiny artifacts (no network)
        run: |
          python - <<'PY'
          import runpy
          g = runpy.run_path('scripts/01_pull_nflverse.py')
          g['weekly_canonicalize']()
          g['rosters_canonicalize']()
          PY

      - name: Step 01b (Pull NGS - temporarily disabled)
        run: |
          echo "NOTE: NGS ingestion disabled — circle back when feed is live."

      - name: Upload raw snapshot (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: nflverse-raw-${{ github.run_id }}
          path: |
            data/raw/nflverse/play_by_play_latest.csv.gz
            data/raw/nflverse/pbp_latest.parquet
            data/raw/nflverse/pbp_latest.head100.csv.gz
            data/raw/nflverse/manifest_latest.csv.gz
            data/raw/nflverse/weekly_latest.csv.gz
            data/raw/nflverse/weekly_latest.parquet
            data/raw/nflverse/weekly_manifest_latest.csv.gz
            data/raw/nflverse/rosters_latest.csv.gz
            data/raw/nflverse/rosters_latest.parquet
            data/raw/nflverse/rosters_manifest_latest.csv.gz

      - name: Commit outputs (raw + models + metrics)
        env:
          GH_USER_NAME: "github-actions[bot]"
          GH_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          set -e
          git config user.name "$GH_USER_NAME"
          git config user.email "$GH_USER_EMAIL"

          mkdir -p data/raw/nflverse
          git add -A -f data/raw/nflverse
          git add -A -f models/pregame
          git add -A -f output/models

          git diff --staged --quiet || git commit -m "Add models and metrics; update raw artifacts"
          git pull --rebase origin main || true
          git push

      - name: Step 02 (Build features)
        run: |
          if [ -f scripts/02_build_features.py ]; then
            python scripts/02_build_features.py
          else
            echo "ERROR: scripts/02_build_features.py not found" && exit 1
          fi

      - name: Step 03 (Train models)
        run: |
          if [ -f scripts/03_train_models.py ]; then
            python scripts/03_train_models.py
          else
            echo "ERROR: scripts/03_train_models.py not found" && exit 1
          fi

      # ===== Step 04: Pregame predictions =====
      - name: Step 04 (Pregame predictions)
        run: |
          python scripts/04_predict_pregame.py --season "${{ env.FORECAST_SEASON }}" --week "${{ env.FORECAST_WEEK }}"

      - name: Upload predictions (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: pregame-predictions-${{ github.run_id }}
          path: |
            output/predictions/pregame/*.csv.gz

      - name: Commit predictions
        env:
          GH_USER_NAME: "github-actions[bot]"
          GH_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        run: |
          set -e
          git config user.name "$GH_USER_NAME"
          git config user.email "$GH_USER_EMAIL"

          mkdir -p data/predictions/pregame output/predictions/pregame
          git add -A -f data/predictions/pregame
          git add -A -f output/predictions/pregame

          git diff --staged --quiet || git commit -m "Add pregame predictions"
          git pull --rebase origin main || true
          git push
