name: odds_fetch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TARGET_SEASON: '2025'
      ODDS_FEATURED_MARKETS: "h2h,spreads,totals"
      # EXACT player prop keys (per-event endpoint). These must be valid Odds API keys.
      ODDS_PLAYER_MARKETS: >-
        player_field_goals_made,player_kicking_points,player_pass_interceptions,
        player_pass_rush_yds,player_pass_tds,player_pass_yds,player_receptions,
        player_reception_yds,player_rush_attempts,player_rush_yds,player_sacks,
        player_solo_tackles,player_tackles_assists,player_anytime_td
      ODDS_REGIONS: "us"
      ODDS_ODDS_FORMAT: "american"
      ODDS_DATE_FORMAT: "iso"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python - <<'PY'
          import importlib, subprocess, sys
          for pkg in ("pandas","requests"):
              try:
                  importlib.import_module(pkg)
              except Exception:
                  subprocess.check_call([sys.executable,"-m","pip","install",pkg])
          PY

      - name: Fetch raw odds/props (featured + per-event player props)
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
          ODDS_FEATURED_MARKETS: ${{ env.ODDS_FEATURED_MARKETS }}
          ODDS_PLAYER_MARKETS: ${{ env.ODDS_PLAYER_MARKETS }}
          ODDS_REGIONS: ${{ env.ODDS_REGIONS }}
          ODDS_ODDS_FORMAT: ${{ env.ODDS_ODDS_FORMAT }}
          ODDS_DATE_FORMAT: ${{ env.ODDS_DATE_FORMAT }}
          TARGET_SEASON: ${{ env.TARGET_SEASON }}
        run: python scripts/01_fetch_odds.py

      - name: Verify props_current.csv exists
        run: test -s data/props/props_current.csv

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit refreshed props_current (only if changed)
        run: |
          git add data/props/props_current.csv -f || true
          git commit -m "[odds] refresh props_current" || true
          git push || true
