name: Odds Fetch (API)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes (UTC)

permissions:
  contents: write

jobs:
  fetch-and-build-props-current:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ensure data dirs
        run: |
          mkdir -p data/props data/logs

      - name: Fetch raw odds/props
        run: python scripts/01_fetch_odds.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

      - name: Canonicalize raw props feed
        run: python scripts/01_canonicalize_raw.py

      - name: Verify props_current.csv exists
        run: |
          test -s data/props/props_current.csv || (echo "props_current.csv missing after canonicalize" && exit 1)

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit refreshed props_current
        run: |
          git add data/props/props_current.csv -f
          git commit -m "[fetch] refresh props_current" || echo "No changes to commit"
          git push || true

      - name: Upload artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: props-current-${{ github.run_id }}
          path: data/props/props_current.csv
          if-no-files-found: error
          retention-days: 3
