# .github/workflows/refresh.yml
name: Weekly Data Refresh

on:
  schedule:
    # Every Tuesday at 17:00 UTC (1:00 PM ET)
    - cron: "0 17 * * 2"
  workflow_dispatch:

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Parquet writer for rosters/weekly/depth if needed
          pip install pyarrow fastparquet || true

      - name: Pull core NFL datasets (weekly/pbp/rosters/depth)
        env:
          NFLVERSE_WEEKLY_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/weekly/weekly_{year}.csv.gz"
          NFLVERSE_ROSTERS_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/rosters/rosters_{year}.csv.gz"
          NFLVERSE_DEPTH_URL_TPL:   "https://github.com/nflverse/nflverse-data/releases/download/depth_charts/depth_charts_{year}.csv.gz"
        run: |
          python scripts/01_pull_nflverse.py --start 2019 --dl-weekly --dl-rosters --dl-depth

      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f data/raw/nflverse
          git commit -m "chore(data): weekly refresh (nflverse) [skip ci]" || echo "No changes to commit"
          git push
