# .github/workflows/refresh.yml
name: Weekly Data Refresh

on:
  schedule:
    - cron: "0 17 * * 2"   # Tuesdays 17:00 UTC
  workflow_dispatch:

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ----- R step for depth charts via nflreadr (writes CSV then gzip to avoid truncation) -----
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R deps (nflreadr)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::nflreadr

      - name: Fetch depth charts (write CSV then gzip)
        run: |
          Rscript - <<'RSCRIPT'
          dir.create("data/raw/nflverse", recursive = TRUE, showWarnings = FALSE)
          suppressPackageStartupMessages(library(nflreadr))
          dc <- nflreadr::load_depth_charts()
          if (nrow(dc) == 0) stop("No depth chart rows returned")
          out_csv <- file.path("data/raw/nflverse","depth_charts.csv")
          write.csv(dc, out_csv, row.names = FALSE)
          cat("Wrote:", out_csv, "\n")
          RSCRIPT
          gzip -f data/raw/nflverse/depth_charts.csv

      # ----- Python setup -----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyarrow fastparquet || true

      # ----- Core nflverse pulls (pbp/weekly/rosters + depth canonicalize) -----
      - name: Pull core NFL datasets (pbp/weekly/rosters/depth)
        env:
          NFLVERSE_WEEKLY_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/weekly/weekly_{year}.csv.gz"
          NFLVERSE_ROSTERS_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/rosters/rosters_{year}.csv.gz"
          NFLVERSE_DEPTH_URL_TPL: ""
        run: |
          python scripts/01_pull_nflverse.py --start 2019 --dl-weekly --dl-rosters --dl-depth

      # ----- WEATHER (newly added) -----
      - name: Pull game weather (Open-Meteo)
        run: |
          python scripts/pull_weather_openmeteo.py

      # ----- INJURIES / ACTIVES (newly added) -----
      - name: Pull injuries & actives
        run: |
          python scripts/pull_injuries_actives.py

      # ----- ODDS API (newly added) -----
      - name: Pull odds via Odds API
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/06_pull_odds_api.py

      - name: Merge/process odds
        run: |
          python scripts/05_pull_odds_merge.py

      # ----- Commit & push updated data -----
      - name: Commit & push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # nflverse core
          git add -f data/raw/nflverse
          # weather + injuries
          git add -f data/raw/weather || true
          git add -f data/raw/injuries || true
          # odds outputs (raw/processed)
          git add -f data/odds || true
          git commit -m "chore(data): weekly refresh (nflverse + weather + injuries + odds) [skip ci]" || echo "No changes to commit"
          git push
