# .github/workflows/refresh.yml
name: Weekly Data Refresh

on:
  schedule:
    - cron: "0 17 * * 2"   # 17:00 UTC = 12:00 PM ET (Tuesday)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- R: depth charts via nflreadr ----------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R deps (nflreadr)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::nflreadr

      - name: Fetch depth charts (CSV then gzip)
        run: |
          Rscript - <<'RSCRIPT'
          dir.create("data/raw/nflverse", recursive = TRUE, showWarnings = FALSE)
          suppressPackageStartupMessages(library(nflreadr))
          dc <- nflreadr::load_depth_charts()
          if (nrow(dc) == 0) stop("No depth chart rows returned")
          out_csv <- file.path("data/raw/nflverse","depth_charts.csv")
          write.csv(dc, out_csv, row.names = FALSE)
          cat("Wrote:", out_csv, "\n")
          RSCRIPT
          gzip -f data/raw/nflverse/depth_charts.csv

      # ---------- Python pulls ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyarrow fastparquet lxml || true

      - name: Pull core NFL datasets (pbp/weekly/rosters/depth)
        env:
          NFLVERSE_WEEKLY_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/weekly/weekly_{year}.csv.gz"
          NFLVERSE_ROSTERS_URL_TPL: "https://github.com/nflverse/nflverse-data/releases/download/rosters/rosters_{year}.csv.gz"
        run: |
          python scripts/01_pull_nflverse.py --start 2019 --dl-weekly --dl-rosters --dl-depth || true

      - name: Pull game weather (Open-Meteo)
        run: |
          python scripts/pull_weather_openmeteo.py || true

      - name: Pull injuries & actives
        run: |
          python scripts/pull_injuries_actives.py || true

      - name: Pull odds via Odds API
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: |
          python scripts/06_pull_odds_api.py || true

      - name: Merge/process odds
        run: |
          python scripts/05_pull_odds_merge.py || true

      # ---------- NEW: build data/weekly/latest.csv robustly ----------
      - name: Build data/weekly/latest.csv from newest weekly file
        run: |
          set -e
          mkdir -p data/weekly
          # Prefer explicit output if your script supports it
          if python - <<'PY'
import os, sys, subprocess
out = "data/weekly/latest.csv"
# If latest.csv already exists from prior step, keep it
sys.exit(0 if os.path.isfile(out) else 1)
PY
          then
            echo "latest.csv already present from previous step."
          else
            # Fallback: pick the newest weekly csv/csv.gz produced by pulls
            latest=$(ls -t data/raw/nflverse/weekly_* 2>/dev/null | head -1 || true)
            if [ -z "$latest" ]; then
              echo "No weekly_* file found under data/raw/nflverse; skipping latest.csv build."
              exit 0
            fi
            case "$latest" in
              *.csv.gz) zcat "$latest" > data/weekly/latest.csv ;;
              *.csv)    cp "$latest"    data/weekly/latest.csv ;;
              *)        echo "Unknown weekly file extension: $latest"; exit 0 ;;
            esac
            echo "Wrote data/weekly/latest.csv from $latest"
          fi
          # Show a quick sample if present
          [ -f data/weekly/latest.csv ] && sed -n '1,10p' data/weekly/latest.csv || true

      # ---------- Commit & push ----------
      - name: Commit & push updated data
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage files (guard each so a missing path doesn't fail the job)
          git add -f data/raw/nflverse        2>/dev/null || true
          git add -f data/raw/weather         2>/dev/null || true
          git add -f data/raw/injuries        2>/dev/null || true
          git add -f data/odds                2>/dev/null || true
          [ -f data/weekly/latest.csv ] && git add -f data/weekly/latest.csv || true

          # Create commit only if something staged
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore(data): weekly refresh (nflverse + weather + injuries + odds + weekly latest) [skip ci]"

          # Rebase in case main moved since checkout
          git fetch origin
          git pull --rebase origin main || true

          # Push
          git push
