name: Weekly Data Refresh (2025-locked)

on:
  schedule:
    - cron: "0 17 * * 2"   # 17:00 UTC = 12:00 PM ET (Tuesday)
  workflow_dispatch:
    inputs:
      season:
        description: "Season context (e.g., 2025)"
        required: false
        default: "2025"

permissions:
  contents: write

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    env:
      # If dispatched with an input, use it; otherwise force 2025.
      TARGET_SEASON: ${{ github.event_name == 'workflow_dispatch' && inputs.season || '2025' }}
      PYTHONUTF8: "1"
      TZ: "UTC"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ---------- R: pull weekly for TARGET_SEASON via nflreadr ----------
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install R deps
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::nflreadr
            any::dplyr
            any::readr

      - name: Fetch weekly player stats for TARGET_SEASON
        run: |
          set -e
          Rscript - <<'RSCRIPT'
          suppressPackageStartupMessages({
            library(nflreadr)
            library(dplyr)
            library(readr)
          })
          dir.create("data/raw/nflverse", recursive = TRUE, showWarnings = FALSE)
          seas <- as.integer(Sys.getenv("TARGET_SEASON", "2025"))
          wk <- nflreadr::load_player_stats(seasons = seas)
          if (nrow(wk) == 0) stop(paste("No weekly rows returned for season", seas))
          out_csv <- file.path("data/raw/nflverse","weekly_latest.csv")
          readr::write_csv(wk, out_csv)
          cat("Wrote:", out_csv, "rows:", nrow(wk), "\n")
          RSCRIPT
          gzip -f data/raw/nflverse/weekly_latest.csv
          ls -lh data/raw/nflverse/weekly_latest.csv.gz

      # ---------- Python: optional repo-specific weekly builder ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pandas pyarrow fastparquet || true

      - name: Build data/weekly/latest.csv (prefer repo script if present)
        run: |
          set -e
          mkdir -p data/weekly

          if [ -f scripts/10_build_weekly_latest.py ]; then
            echo "Using scripts/10_build_weekly_latest.py --season ${TARGET_SEASON}"
            python scripts/10_build_weekly_latest.py --season "${TARGET_SEASON}"
            SRC="data/weekly/latest.csv"
            [ -s "$SRC" ] || { echo "ERROR: $SRC not produced by 10_build_weekly_latest.py"; exit 1; }
          else
            echo "Repo builder not found; falling back to nflreadr weekly_latest.csv.gz"
            SRC="data/raw/nflverse/weekly_latest.csv.gz"
            [ -s "$SRC" ] || { echo "ERROR: $SRC not found after nflreadr fetch"; exit 1; }
            zcat "$SRC" > data/weekly/latest.csv
          fi

          echo "✓ Ensured data/weekly/latest.csv exists"
          sed -n '1,20p' data/weekly/latest.csv || true

      # ---------- Verify season/week coverage (HARD-FAIL if not 2025) ----------
      - name: Verify data/weekly/latest.csv is for TARGET_SEASON
        run: |
          set -e
          python - <<'PY'
          import os, sys, pandas as pd
          want = int(os.getenv("TARGET_SEASON","2025"))
          p = "data/weekly/latest.csv"
          if not os.path.exists(p): 
              print(f"ERROR: {p} missing", file=sys.stderr); sys.exit(1)
          df = pd.read_csv(p)
          for col in ("season","week"):
              if col not in df.columns:
                  print(f"ERROR: {p} missing '{col}' column", file=sys.stderr); sys.exit(1)
          mx = int(pd.to_numeric(df["season"], errors="coerce").max())
          by = df.groupby("season")["week"].max().to_dict()
          print("max(season)=", mx, "max week per season=", {int(k): int(v) for k,v in by.items()})
          if mx != want:
              print(f"ERROR: {p} max(season)={mx} != {want}.", file=sys.stderr); sys.exit(1)
          PY

      # ---------- Commit & push (force-add data paths) ----------
      - name: Commit & push updated data
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f data/raw/nflverse/weekly_latest.csv.gz 2>/dev/null || true
          git add -f data/weekly/latest.csv                  2>/dev/null || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "refresh: weekly data (TARGET_SEASON=${TARGET_SEASON})"
          git fetch origin main || true
          git pull --rebase --autostash origin main || true
          git push origin HEAD:main
