name: stage-pending

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create history_pending.csv from props_current.csv
        run: |
          python scripts/08a_stage_pending_from_current.py

      - name: Commit pending
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || git merge --no-edit origin/main
          git add -f data/props/history_pending.csv
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Stage pending props from props_current (run $GITHUB_RUN_ID)"
          git push origin HEAD:main
