name: sync-schedules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * 2,5"  # Tue/Fri 11:00 UTC

permissions:
  contents: write

jobs:
  schedules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas pyarrow python-dateutil pyyaml

      - name: Ensure whitelist and reports tracking
        run: |
          mkdir -p data/processed/schedules
          cat > data/processed/schedules/.gitignore <<'EOF'
          *
          !.gitignore
          !schedules_merged.csv
          !schedules_normalized.csv
          EOF
          mkdir -p output/reports
          printf "*\n!.gitignore\n!schedule_validation_errors.csv\n!schedule_dupes.csv\n!schedule_summary.csv\n!unique_teams.csv\n" > output/reports/.gitignore

      # --- NEW: Ensure schema file exists in CI even if not committed ---
      - name: Ensure schedule schema file
        run: |
          mkdir -p config/schemas
          cat > config/schemas/schedule_schema.yml <<'YAML'
          version: 1
          name: schedule_schema
          description: Canonical schema for normalized NFL schedules
          fields:
            - name: season
              type: int
              required: true
            - name: season_type
              type: enum
              values: [preseason, regular, postseason]
              required: true
            - name: week
              type: int
              required: true
            - name: game_date_utc
              type: date
              required: true
            - name: game_time_utc
              type: time
              required: true
            - name: home_team
              type: string
              required: true
            - name: away_team
              type: string
              required: true
            - name: home_team_id
              type: string
              required: false
            - name: away_team_id
              type: string
              required: false
            - name: venue
              type: string
              required: false
            - name: venue_city
              type: string
              required: false
            - name: venue_state
              type: string
              required: false
            - name: game_status
              type: enum
              values: [scheduled, in_progress, final, postponed, canceled]
              required: true
            - name: source
              type: string
              required: true
            - name: source_event_id
              type: string
              required: true
            - name: canonical_game_id
              type: string
              required: false
            - name: canonical_hash
              type: string
              required: false
          constraints:
            unique:
              - [season, season_type, week, home_team, away_team, game_date_utc, game_time_utc]
              - [canonical_game_id]
            non_null:
              - [season, season_type, week, game_date_utc, game_time_utc, home_team, away_team, source, source_event_id]
          YAML

      - name: Sync schedules (2024, 2025)
        run: |
          python scripts/00_sync_schedules.py

      - name: Stage schedules (raw → staging)
        run: |
          python scripts/02_load_schedules.py

      # --- NEW: Assert staged file exists (fail-fast if missing) ---
      - name: Assert staged exists
        run: |
          test -s data/processed/schedules/_staging/schedules_staged.csv

      - name: Prepare team mapping skeleton
        run: |
          python scripts/03a_prepare_team_mapping_skeleton.py

      - name: Normalize IDs (staging → normalized)
        run: |
          python scripts/03_normalize_ids.py

      - name: Validate normalized schedules
        run: |
          python scripts/04_validate_schedules.py

      - name: Upload artifacts (staged, normalized, reports)
        uses: actions/upload-artifact@v4
        with:
          name: schedules-artifacts
          path: |
            data/processed/schedules/_staging/schedules_staged.csv
            data/processed/schedules/_staging/schedules_staged.parquet
            data/processed/schedules/schedules_normalized.csv
            data/processed/schedules/schedules_normalized.parquet
            output/reports/schedule_validation_errors.csv
            output/reports/schedule_dupes.csv
            output/reports/schedule_summary.csv
            output/reports/unique_teams.csv
          if-no-files-found: warn

      - name: Commit schedules and reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add config/schemas/schedule_schema.yml || true
          git add data/raw/schedules/schedules_2024.csv || true
          git add data/raw/schedules/schedules_2025.csv || true
          git add data/processed/schedules/.gitignore || true
          git add data/processed/schedules/schedules_merged.csv || true
          git add data/processed/schedules/schedules_normalized.csv || true
          git add output/reports/.gitignore || true
          git add output/reports/schedule_validation_errors.csv || true
          git add output/reports/schedule_dupes.csv || true
          git add output/reports/schedule_summary.csv || true
          git add output/reports/unique_teams.csv || true
          git commit -m "chore: ensure schema, stage assert, sync→stage→map→normalize→validate" || echo "No changes to commit"
          git push
